#!/usr/bin/env python3
"""
NEEL Lab website · 번역 사전 관리 (KO ⇄ EN)
-----------------------------------------------------------------
구글 사이트에서 가져온 내용(data/content.json)은 그대로 두고,
화면 언어에 맞는 번역문만 data/i18n.json → data/i18n.js 로 관리합니다.

  - EN 모드: 한글이 들어 있는 문장은 영어 번역으로 표시
  - KO 모드: 현재 구성원의 역할/관심분야 같은 짧은 영어 문장은 한국어로 표시
    (논문 제목·학회 발표·수상명 같은 학술 기록은 원문 그대로 둡니다)

번역문은 문장 원문의 해시(FNV-1a, 공백 정규화)로 찾습니다. app.js 의 hkey() 와 같은 규칙입니다.

사용법
  python3 sync/i18n.py --status                 # 번역이 빠진 문장 수
  python3 sync/i18n.py --export missing.json    # 번역할 문장 내보내기 [{id, lang, text}]
  python3 sync/i18n.py --import done.json       # 번역 결과 합치기   [{id, lang, text}]
  python3 sync/i18n.py --auto https://…/translate   # 빠진 문장을 AI 프록시로 자동 번역 (I18N_TOKEN 환경변수)
  python3 sync/i18n.py --build                  # data/i18n.js 만 다시 만들기
"""
import argparse
import json
import os
import re
import sys
import urllib.request

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
CONTENT = os.path.join(ROOT, "data", "content.json")
STORE = os.path.join(ROOT, "data", "i18n.json")
OUT_JS = os.path.join(ROOT, "data", "i18n.js")

HANGUL = re.compile(r"[가-힣]")
# never translated: file/URL refs, ids, and fields that already exist in both languages
SKIP_KEYS = {"key", "ref", "file", "src", "href", "url", "doi", "pdf", "image", "images", "banner", "photo", "slides",
             "thumb", "id", "slug", "date", "name", "name_ko", "name_en", "nick", "title_ko", "title_en", "image_dims"}
# Google-Sites pages that have their own renderer in app.js — their raw blocks are never shown
RENDERED = {"home", "news", "news/research-news", "course", "members", "professor", "publication", "publication/cover",
            "research", "program", "project", "patent", "presentation", "award", "neelstagram", "contact"}


def norm(s):
    return re.sub(r"\s+", " ", s).strip()


def hkey(s):
    x = 0x811C9DC5
    for b in norm(s).encode("utf-8"):
        x ^= b
        x = (x * 0x01000193) & 0xFFFFFFFF
    return format(x, "08x")


def visible_text(s):
    return norm(re.sub(r"<[^>]+>", " ", s).replace("&nbsp;", " "))


def collect(data):
    """→ {lang: {id: source}} of every displayed string that needs a translation for that language."""
    need = {"en": {}, "ko": {}}

    def walk(o, key=None):
        if isinstance(o, dict):
            # a Korean-only title (no English sibling) is shown translated in EN mode
            if isinstance(o.get("title_ko"), str) and not o.get("title_en") and HANGUL.search(o["title_ko"]):
                need["en"][hkey(o["title_ko"])] = o["title_ko"]
            for k, v in o.items():
                if k not in SKIP_KEYS:
                    walk(v, k)
        elif isinstance(o, list):
            for v in o:
                walk(v, key)
        elif isinstance(o, str) and HANGUL.search(o) and visible_text(o):
            need["en"][hkey(o)] = o

    for top, v in data.items():
        if top == "pages":
            for slug, page in v.items():
                if slug not in RENDERED:
                    walk(page)
        elif top not in SKIP_KEYS:
            walk(v, top)
    # KO: member roles / interests / current positions, and the professor's English-only CV lines
    def ko(s):
        if isinstance(s, str) and not HANGUL.search(s) and re.search(r"[A-Za-z]{3,}", visible_text(s)):
            need["ko"][hkey(s)] = s
    for g in data.get("members", []):
        for m in g.get("members", []):
            for r in m.get("roles", []):
                ko(r)
    prof = data.get("professor", {})
    for e in prof.get("education", []) + prof.get("experience", []):
        ko(e.get("html")); ko(e.get("text"))
    for grp in prof.get("activities", []):
        for it in grp.get("items", []):
            ko(it.get("html"))
    return need


def load_store():
    try:
        return json.load(open(STORE, encoding="utf-8"))
    except Exception:
        return {"en": {}, "ko": {}}


def save_store(store):
    for lang in ("en", "ko"):
        store[lang] = dict(sorted(store.get(lang, {}).items()))
    with open(STORE, "w", encoding="utf-8") as f:
        json.dump(store, f, ensure_ascii=False, indent=1)
    build_js(store)


def build_js(store):
    data = json.load(open(CONTENT, encoding="utf-8"))
    need = collect(data)
    # ship only translations that are still used (sources removed from the Google Site drop out)
    compact = {lang: {h: rec["t"] for h, rec in store.get(lang, {}).items() if h in need[lang] and rec.get("t")} for lang in ("en", "ko")}
    with open(OUT_JS, "w", encoding="utf-8") as f:
        f.write("/* generated by sync/i18n.py — edit data/i18n.json, not this file */\n")
        f.write("window.NEEL_I18N = " + json.dumps(compact, ensure_ascii=False, separators=(",", ":")) + ";\n")
    return compact


def missing(store, need):
    out = []
    for lang in ("en", "ko"):
        have = store.get(lang, {})
        for h, src in need[lang].items():
            rec = have.get(h)
            if not rec or not rec.get("t"):
                out.append({"id": h, "lang": lang, "text": src})
    return out


def merge(store, items, need):
    n = 0
    for it in items:
        lang, h, t = it.get("lang"), it.get("id"), (it.get("text") or "").strip()
        src = need.get(lang, {}).get(h)
        if not (lang in ("en", "ko") and src and t):
            continue
        store.setdefault(lang, {})[h] = {"s": src, "t": t}
        n += 1
    return n


def auto(store, need, endpoint, batch=12):
    token = os.environ.get("I18N_TOKEN", "")
    todo = missing(store, need)
    if not todo:
        print("i18n: nothing to translate")
        return 0
    print("i18n: translating %d strings via %s" % (len(todo), endpoint))
    done = 0
    for i in range(0, len(todo), batch):
        chunk = todo[i:i + batch]
        for lang in ("en", "ko"):
            part = [c for c in chunk if c["lang"] == lang]
            if not part:
                continue
            body = json.dumps({"target": lang, "items": [{"id": c["id"], "text": c["text"]} for c in part]}).encode("utf-8")
            req = urllib.request.Request(endpoint, data=body, method="POST", headers={"Content-Type": "application/json", "X-I18N-Token": token, "Origin": "https://usim-lab.github.io", "User-Agent": "neel-sync/1.0 (+https://usim-lab.github.io)"})
            try:
                with urllib.request.urlopen(req, timeout=120) as r:
                    res = json.load(r)
                done += merge(store, [{"id": x["id"], "lang": lang, "text": x.get("text", "")} for x in res.get("items", [])], need)
            except Exception as e:
                print("   ! batch failed:", e)
    print("i18n: %d translated" % done)
    return done


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--status", action="store_true")
    ap.add_argument("--export")
    ap.add_argument("--import", dest="imp")
    ap.add_argument("--auto")
    ap.add_argument("--build", action="store_true")
    a = ap.parse_args()
    data = json.load(open(CONTENT, encoding="utf-8"))
    need = collect(data)
    store = load_store()
    if a.imp:
        items = json.load(open(a.imp, encoding="utf-8"))
        print("imported", merge(store, items, need))
        save_store(store)
    if a.auto:
        if auto(store, need, a.auto):
            save_store(store)
    if a.export:
        miss = missing(store, need)
        json.dump(miss, open(a.export, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
        print("exported", len(miss))
    if a.build:
        build_js(store)
    miss = missing(store, need)
    print("i18n status: en %d/%d, ko %d/%d translated" % (
        len(need["en"]) - sum(1 for m in miss if m["lang"] == "en"), len(need["en"]),
        len(need["ko"]) - sum(1 for m in miss if m["lang"] == "ko"), len(need["ko"])))
    if not os.path.exists(OUT_JS):
        build_js(store)


if __name__ == "__main__":
    sys.exit(main())
